version: 2.1

orbs:
  node: circleci/node@5.1.0

aliases:
  # Forward the current folder when using workflows
  - &persist_work_dir
    root: .
    paths:
      - .

  - &attach_work_dir
    at: ~/repo

jobs:
  # Step build
  build:
    docker:
      - image: cimg/node:16.17.0

    working_directory: ~/repo

    steps:
      - checkout
      - persist_to_workspace: *persist_work_dir

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Build
          command: yarn build

      - run:
          name: Test
          command: yarn test

      - persist_to_workspace: *persist_work_dir
      - store_test_results:
          path: junit/

  # Step release
  release:
    docker:
      - image: cimg/node:16.17.0
    working_directory: ~/repo
    steps:
      - attach_workspace: *attach_work_dir

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Release
          command: yarn semantic-release
      - run:
          name: Docker Build
          command: yarn docker:build
      - run:
          name: Docker publish
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            yarn docker:release

workflows:
  suite:
    jobs:
      - build

      - release:
          requires:
            - build
          filters:
            branches:
              only: master
