version: 2.1

orbs:
  node: circleci/node@4.5.0

jobs:
  build:
    docker:
      - image: cimg/node:14.16.1

    working_directory: ~/repo

    steps:
      - checkout

      - node/install-packages:
                pkg-manager: yarn

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Build
          command: yarn build

      - run:
          name: Test
          command: yarn test

      - store_test_results:
          path: junit/

workflows:
  suite:
    jobs:
      - build
