#!/bin/sh
# Some of our unit tests assert that the external third party APIs we are using
# return data in an expected format. They query the relevant API with real (not
# mocked) HTTP calls.
#
# Those tests are slow, and have a higher probability of flakiness because of
# network issues or timeouts. We don't want to run them on each pre-commit hook
# or CI commit, so we extracted them into a specific folder and excluded that
# folder from the normal run.
#
# This script is doing the opposite: it only runs those very important, yet
# slow and potentially unstable, tests. The CI is configured to run it
# periodically and create an issue if it fails.
set -e

jest \
	./src/__tests__/sanity-check \
	--forceExit \
	--testPathIgnorePatterns=''
