#!/bin/sh
# API Control tests assert that the external third party APIs we are using
# return data in an expected format. They query the relevant API with real (not
# mocked) HTTP calls.
#
# As those tests are slow, and have a higher probability of flakiness because of
# network issues or timeouts, we don't want to run them on each pre-commit hook
# or CI commit. They can instead be run manually, or periodically from the CI.
#
# When it fails on the CI, it will generate a GitHub issue with the failure details
# as well as a link to the run.

# Running locally, with colors and live output
if [ "$GITHUB_RUN_ID" = "" ]; then
	jest \
		./src/__tests__/api-control \
		--forceExit \
		--testPathIgnorePatterns=''
	exit $?
fi

# Running on CI, creating an issue on failure
echo "Wait while we run the tests"
output=$(jest \
	./src/__tests__/api-control \
	--forceExit \
	--testPathIgnorePatterns='' 2>&1)
exitCode=$?
echo "$output"

# Stop on success
if [ "$exitCode" = "0" ]; then
	exit 0
fi

# Create the issue on failure
gh issue create \
	--title "API Control failed" \
	--body "\
One of the external APIs we depend on failed to return coherent data in our periodic test.
Maybe it's a temporary issue, maybe they changed their format.

https://github.com/algolia/npm-search/actions/runs/$GITHUB_RUN_ID

\`\`\`
$output
\`\`\`"

# Still mark the job as failed
exit 1
