name: CANCEL CURL

on:
  push:
    branches:
      - fix/issue-1233-docker-publishing

jobs:
  cancel:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RUN_ID: ${{ github.run_id }}

    steps:
      - name: Curl
        run: 'curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/algolia/npm-search/actions/runs/${RUN_ID}/cancel"'
